language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "arkokoley@arkoman.cu.cc"

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: nxt_travis

before_script:
  - mysql -e 'create database nxt-travis;'
  - mysql nxt_travis < nxt-content/nxt_travis.sql